(repository
  (url "http://seth-misc.s3-website-us-east-1.amazonaws.com/index.scm")
  (name "incomplete or written while drunk")
  (sibling
    (name "Snow2 Repository")
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/index.scm")
    (trust 1.0))
  (package
    (name (image))
    (version "1.0")
    (url "image.tgz")
    (size 31744)
    (checksum (md5 "55fc8575395370a39103a6f54b5d347b"))
    (library
      (name (seth image))
      (path "seth/image.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (manual)
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "read and write netimage files.")
      (license BSD-style)
      (depends (seth raster))
      (use-for final))
    (library
      (name (seth image tests))
      (path "seth/image/tests.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (manual)
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "tests for (seth image)")
      (license BSD-style)
      (depends (seth cout) (seth raster) (seth image))
      (use-for test)))
  (package
    (name (raster))
    (version "1.0")
    (url "raster.tgz")
    (size 12800)
    (checksum (md5 "b7a07a5276a3a2b373ce1c2b1a005b63"))
    (library
      (name (seth raster))
      (path "seth/raster.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (manual)
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "read and write netraster files.")
      (license BSD-style)
      (depends)
      (use-for final))
    (library
      (name (seth raster tests))
      (path "seth/raster/tests.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (manual)
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "tests for (seth raster)")
      (license BSD-style)
      (depends (seth cout) (seth raster))
      (use-for test)))
  (package
    (name (pbm))
    (version "1.0")
    (url "pbm.tgz")
    (size 12800)
    (checksum (md5 "a1f2e3dba49ea5ae2ff074dac3fd0bd5"))
    (library
      (name (seth pbm))
      (path "seth/pbm.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (manual)
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "read and write netpbm files.")
      (license BSD-style)
      (depends (srfi 60) (seth cout) (seth raster) (seth image))
      (use-for final))
    (library
      (name (seth pbm tests))
      (path "seth/pbm/tests.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (manual)
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "tests for (seth pbm)")
      (license BSD-style)
      (depends (seth pbm))
      (use-for test)))
  (package
    (name (scheme-read))
    (version "1.0")
    (url "scheme-read.tgz")
    (size 68608)
    (checksum (md5 "ed4e34aa222eb6d0bbd57e2f54f09642"))
    (library
      (name (seth scheme-read))
      (path "seth/scheme-read.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (manual)
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "read scheme and keep track of whitespace.")
      (license BSD-style)
      (depends (seth flex) (seth port-extras))
      (use-for final))
    (library
      (name (seth-tests scheme-read tests))
      (path "seth-tests/scheme-read/tests.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (manual)
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "tests for (seth scheme-read)")
      (license BSD-style)
      (depends (seth scheme-read) (seth port-extras))
      (use-for test)))
  (package
    (name ())
    (version "1.0")
    (url "minecraft-nbt.tgz")
    (size 14848)
    (checksum (md5 "16beb58dfc66ca7b507061f9d172fda8"))
    (library
      (name (seth minecraft-nbt))
      (path "seth/minecraft-nbt.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (manual (else "http://minecraft.gamepedia.com/NBT_format"))
      (maintainers "Seth Alves <alves@hungry.com>")
      (authors "Seth Alves <alves@hungry.com>")
      (description "The Named Binary Tag format used by Minecraft")
      (license bsd)
      (depends (snow genport) (snow zlib) (snow assert) (weinholt struct pack))
      (use-for final))
    (library
      (name (seth minecraft-nbt tests))
      (path "seth/minecraft-nbt/tests.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (manual)
      (maintainers "Seth Alves <alves@hungry.com>")
      (authors "Seth Alves <alves@hungry.com>")
      (description "tests for minecraft-nbt")
      (license bsd)
      (depends (snow extio) (seth minecraft-nbt))
      (use-for test)))
  (package
    (name (flex))
    (version "1.0")
    (url "flex.tgz")
    (size 17408)
    (checksum (md5 "83e30e1e6f3aaf55901a8d269e2a7cc5"))
    (library
      (name (seth flex))
      (path "seth/flex.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (manual)
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "run a flex tokenizer in scheme")
      (license BSD-style)
      (depends)
      (use-for final))
    (library
      (name (seth-tests flex tests))
      (path "seth-tests/flex/tests.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (manual)
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "tests for (seth flex)")
      (license BSD-style)
      (depends (seth flex) (seth port-extras))
      (use-for test))))
